cfenv-prefix
This change fixes cfenv-prefix.

diff --git a/libexec/cfenv-prefix b/libexec/cfenv-prefix
--- a/libexec/cfenv-prefix
+++ b/libexec/cfenv-prefix
@@ -1,41 +1,41 @@
 #!/usr/bin/env bash
-# Summary: Display prefix for a Ruby version
-# Usage: rbenv prefix [<version>]
+# Summary: Display prefix for a Cloud Foundry environment
+# Usage: cfenv prefix [<environment>]
 #
-# Displays the directory where a Ruby version is installed. If no
-# version is given, `rbenv prefix' displays the location of the
-# currently selected version.
+# Displays the directory where a Cloud Foundry environment is installed. If no
+# environment is given, `cfenv prefix' displays the location of the
+# currently selected environment.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$CFENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide cfenv completions
 if [ "$1" = "--complete" ]; then
   echo system
-  exec rbenv-versions --bare
+  exec cfenv-environments --bare
 fi
 
 if [ -n "$1" ]; then
-  export RBENV_VERSION="$1"
-elif [ -z "$RBENV_VERSION" ]; then
-  RBENV_VERSION="$(rbenv-version-name)"
+  export CFENV_ENVIRONMENT="$1"
+elif [ -z "$CFENV_ENVIRONMENT" ]; then
+  CFENV_ENVIRONMENT="$(cfenv-environment-name)"
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  if RUBY_PATH="$(rbenv-which ruby 2>/dev/null)"; then
-    RUBY_PATH="${RUBY_PATH%/*}"
-    echo "${RUBY_PATH%/bin}"
+if [ "$CFENV_ENVIRONMENT" = "system" ]; then
+  if CF_PATH="$(cfenv-which cf 2>/dev/null)"; then
+    CF_PATH="${CF_PATH%/*}"
+    echo "${CF_PATH%/bin}"
     exit
   else
-    echo "rbenv: system version not found in PATH" >&2
+    echo "cfenv: system environment not found in PATH" >&2
     exit 1
   fi
 fi
 
-RBENV_PREFIX_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}"
-if [ ! -d "$RBENV_PREFIX_PATH" ]; then
-  echo "rbenv: version \`${RBENV_VERSION}' not installed" >&2
+CFENV_PREFIX_PATH="${CFENV_ROOT}/environments/${CFENV_ENVIRONMENT}"
+if [ ! -d "$CFENV_PREFIX_PATH" ]; then
+  echo "cfenv: environment \`${CFENV_ENVIRONMENT}' not installed" >&2
   exit 1
 fi
 
-echo "$RBENV_PREFIX_PATH"
+echo "$CFENV_PREFIX_PATH"
