cfenv-which
This change fixes cfenv-which.

diff --git a/libexec/cfenv-which b/libexec/cfenv-which
--- a/libexec/cfenv-which
+++ b/libexec/cfenv-which
@@ -2,17 +2,17 @@
 #
 # Summary: Display the full path to an executable
 #
-# Usage: rbenv which <command>
+# Usage: cfenv which <command>
 #
-# Displays the full path to the executable that rbenv will invoke when
+# Displays the full path to the executable that cfenv will invoke when
 # you run the given command.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$CFENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide cfenv completions
 if [ "$1" = "--complete" ]; then
-  exec rbenv shims --short
+  exec cfenv shims --short
 fi
 
 expand_path() {
@@ -48,38 +48,38 @@ remove_from_path() {
   echo "${result%:}"
 }
 
-RBENV_VERSION="$(rbenv-version-name)"
-RBENV_COMMAND="$1"
+CFENV_ENVIRONMENT="$(cfenv-environment-name)"
+CFENV_COMMAND="$1"
 
-if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage which >&2
+if [ -z "$CFENV_COMMAND" ]; then
+  cfenv-help --usage which >&2
   exit 1
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  PATH="$(remove_from_path "${RBENV_ROOT}/shims")"
-  RBENV_COMMAND_PATH="$(command -v "$RBENV_COMMAND" || true)"
+if [ "$CFENV_ENVIRONMENT" = "system" ]; then
+  PATH="$(remove_from_path "${CFENV_ROOT}/shims")"
+  CFENV_COMMAND_PATH="$(command -v "$CFENV_COMMAND" || true)"
 else
-  RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
+  CFENV_COMMAND_PATH="${CFENV_ROOT}/environments/${CFENV_ENVIRONMENT}/bin/${CFENV_COMMAND}"
 fi
 
 OLDIFS="$IFS"
-IFS=$'\n' scripts=(`rbenv-hooks which`)
+IFS=$'\n' scripts=(`cfenv-hooks which`)
 IFS="$OLDIFS"
 for script in "${scripts[@]}"; do
   source "$script"
 done
 
-if [ -x "$RBENV_COMMAND_PATH" ]; then
-  echo "$RBENV_COMMAND_PATH"
+if [ -x "$CFENV_COMMAND_PATH" ]; then
+  echo "$CFENV_COMMAND_PATH"
 else
-  echo "rbenv: $RBENV_COMMAND: command not found" >&2
+  echo "cfenv: $CFENV_COMMAND: command not found" >&2
 
-  versions="$(rbenv-whence "$RBENV_COMMAND" || true)"
-  if [ -n "$versions" ]; then
+  environments="$(cfenv-whence "$CFENV_COMMAND" || true)"
+  if [ -n "$environments" ]; then
     { echo
-      echo "The \`$1' command exists in these Ruby versions:"
-      echo "$versions" | sed 's/^/  /g'
+      echo "The \`$1' command exists in these Cloud Foundry environments:"
+      echo "$environments" | sed 's/^/  /g'
       echo
     } >&2
   fi
