cfenv
This change fixes cfenv.

diff --git a/libexec/cfenv b/libexec/cfenv
--- a/libexec/cfenv
+++ b/libexec/cfenv
@@ -3,18 +3,18 @@ set -e
 export -n CDPATH
 
 if [ "$1" = "--debug" ]; then
-  export RBENV_DEBUG=1
+  export CFENV_DEBUG=1
   shift
 fi
 
-if [ -n "$RBENV_DEBUG" ]; then
+if [ -n "$CFENV_DEBUG" ]; then
   export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
   set -x
 fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "cfenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -36,39 +36,39 @@ abs_dirname() {
   cd "$cwd"
 }
 
-if [ -z "${RBENV_ROOT}" ]; then
-  RBENV_ROOT="${HOME}/.rbenv"
+if [ -z "${CFENV_ROOT}" ]; then
+  CFENV_ROOT="${HOME}/.cfenv"
 else
-  RBENV_ROOT="${RBENV_ROOT%/}"
+  CFENV_ROOT="${CFENV_ROOT%/}"
 fi
-export RBENV_ROOT
+export CFENV_ROOT
 
-if [ -z "${RBENV_DIR}" ]; then
-  RBENV_DIR="$(pwd)"
+if [ -z "${CFENV_DIR}" ]; then
+  CFENV_DIR="$(pwd)"
 else
-  cd "$RBENV_DIR" 2>/dev/null || {
-    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
+  cd "$CFENV_DIR" 2>/dev/null || {
+    echo "cfenv: cannot change working directory to \`$CFENV_DIR'"
     exit 1
   } >&2
-  RBENV_DIR="$(pwd)"
+  CFENV_DIR="$(pwd)"
   cd "$OLDPWD"
 fi
-export RBENV_DIR
+export CFENV_DIR
 
 
 shopt -s nullglob
 
 bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
+for plugin_bin in "${CFENV_ROOT}/plugins/"*/bin; do
   bin_path="${bin_path}:${plugin_bin}"
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
+hook_path="${CFENV_HOOK_PATH}:${CFENV_ROOT}/cfenv.d:/usr/local/etc/cfenv.d:/etc/cfenv.d:/usr/lib/cfenv/hooks"
+for plugin_hook in "${CFENV_ROOT}/plugins/"*/etc/cfenv.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
-export RBENV_HOOK_PATH="$hook_path"
+export CFENV_HOOK_PATH="$hook_path"
 
 shopt -u nullglob
 
@@ -76,15 +76,15 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "$(rbenv---version)\n$(rbenv-help)" >&2
+  echo -e "$(cfenv---version)\n$(cfenv-help)" >&2
   ;;
 "-v" )
-  exec rbenv---version
+  exec cfenv---version
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "cfenv-$command" || true)"
   if [ -z "$command_path" ]; then
-    echo "rbenv: no such command \`$command'" >&2
+    echo "cfenv: no such command \`$command'" >&2
     exit 1
   fi
 
